version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
    restart: always
    command: ["flask", "run", "--host=0.0.0.0"]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    env_file:
      - .env
    environment:
      - API_URL=http://backend:5000/api
    depends_on:
      - backend
    restart: always
    command: ["streamlit", "run", "frontend/app.py"]
